server:
  port: 3333
spring:
  application:
    name: my-app
  datasource:
    username: project2
    password: 190701-revature
    url: jdbc:postgresql://rev-postgres.cpq4fhgvtmpk.us-east-2.rds.amazonaws.com:5432/project2
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      current_session_context_class: thread
      format_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
security:
  jwt:
    token:
      secret-key: the-most-secret-key
      expire-length: 3000000000